# Conda environment specification
# Author: Divyansh Kumar Singh (DKS) · M.Tech Civil Engineering (Hydraulic), IIT Kanpur
# GitHub: https://github.com/DKS-MANAGER

name: bridge_condition_xgboost
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - shap
  - matplotlib
  - seaborn
  - joblib
  - pyyaml
  - requests
  - pip
  - pip:
    - -r requirements.txt
